<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>BrewUpApiTemplate</PackageId>
    <PackageVersion>1.0.0</PackageVersion>
    <Title>BrewUp API template</Title>
    <Authors>Alberto Acerbis</Authors>
    <Company>Muflone</Company>
    <Copyright>Alberto Acerbis</Copyright>
    <Description>A project template for creating a modular RESTful WebAPI</Description>
    <PackageTags>Modular Monolith, DDD</PackageTags>
    <PackageProjectUrl>https://github.com/BrewUp/BrewUpApiTemplate</PackageProjectUrl>
    <PackageType>Template</PackageType>
    <TargetFramework>net9.0</TargetFramework>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageIcon>Logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/BrewUp/BrewUpApiTemplate</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup>
    <LocalizeTemplates>false</LocalizeTemplates>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TemplateEngine.Tasks" Version="*" PrivateAssets="all" IsImplicitlyDefined="true"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="content\**\*" Exclude="content\**\bin\**;content\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Logo.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
